-- ==========================================================
-- Migration: Tambah kolom Risk:Reward (SL + TP1-5) ke tabel trades
-- Aman dijalankan berkali-kali (pakai IF NOT EXISTS).
-- Jalankan ini di phpMyAdmin > database kamu > tab SQL, lalu klik Go.
-- ==========================================================

ALTER TABLE trades
  ADD COLUMN IF NOT EXISTS tp1_hit TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tp2_hit TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tp3_hit TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tp4_hit TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tp5_hit TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tp1_price DECIMAL(18,5) NULL,
  ADD COLUMN IF NOT EXISTS tp2_price DECIMAL(18,5) NULL,
  ADD COLUMN IF NOT EXISTS tp3_price DECIMAL(18,5) NULL,
  ADD COLUMN IF NOT EXISTS tp4_price DECIMAL(18,5) NULL,
  ADD COLUMN IF NOT EXISTS tp5_price DECIMAL(18,5) NULL,
  ADD COLUMN IF NOT EXISTS tp1_pips DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS tp1_usd DECIMAL(14,2) NULL,
  ADD COLUMN IF NOT EXISTS tp2_pips DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS tp2_usd DECIMAL(14,2) NULL,
  ADD COLUMN IF NOT EXISTS tp3_pips DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS tp3_usd DECIMAL(14,2) NULL,
  ADD COLUMN IF NOT EXISTS tp4_pips DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS tp4_usd DECIMAL(14,2) NULL,
  ADD COLUMN IF NOT EXISTS tp5_pips DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS tp5_usd DECIMAL(14,2) NULL,
  ADD COLUMN IF NOT EXISTS sl_hit TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sl_pips DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS sl_usd DECIMAL(14,2) NULL;

-- Cek hasilnya:
-- DESCRIBE trades;
