const movieData = [
    {
        title: "Cyber City Adventures Episode 1",
        code: "HDV-001",
        model: "Aoi Tsukada",
        studio: "StudioNeo",
        region: "Japan",
        releaseDate: "2026-01-15",
        duration: "125",
        imgurl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "An action-packed futuristic journey through the neon-lit streets of Tokyo featuring amazing visual effects and intense drama.",
        tags: ["Action", "Cyberpunk", "Drama"]
    },
    {
        title: "Mystic Romance in Seoul",
        code: "HDV-002",
        model: "Park Min-ji",
        studio: "KWave",
        region: "Korea",
        releaseDate: "2026-02-10",
        duration: "110",
        imgurl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "A heartwarming and emotional romance story set against the beautiful backdrop of modern Seoul during spring.",
        tags: ["Romance", "Drama", "Slice of Life"]
    },
    {
        title: "Shanghai Nights Confidential",
        code: "HDV-003",
        model: "Li Wei",
        studio: "DragonMedia",
        region: "China",
        releaseDate: "2026-02-20",
        duration: "140",
        imgurl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "A thrilling undercover investigation story hidden deep within the luxurious nightlife and glamorous clubs of Shanghai.",
        tags: ["Thriller", "Action", "Mystery"]
    },
    {
        title: "Tropical Paradise Getaway",
        code: "HDV-004",
        model: "Siti Rahma",
        studio: "Archipelago",
        region: "Indonesia",
        releaseDate: "2026-03-01",
        duration: "95",
        imgurl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "Enjoy a breathtaking summer escape exploring hidden exotic beaches, traditional local culture, and relaxing vibes.",
        tags: ["Travel", "Slice of Life", "Documentary"]
    },
    {
        title: "Tokyo Undercover Mission",
        code: "HDV-005",
        model: "Aoi Tsukada",
        studio: "StudioNeo",
        region: "Japan",
        releaseDate: "2026-03-05",
        duration: "115",
        imgurl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "High stakes corporate espionage and high-speed chases through the underground expressways of Tokyo.",
        tags: ["Action", "Thriller", "Cyberpunk"]
    },
    {
        title: "Busan Express Sunset",
        code: "HDV-006",
        model: "Park Min-ji",
        studio: "KWave",
        region: "Korea",
        releaseDate: "2026-03-12",
        duration: "105",
        imgurl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "An unexpected encounter on a high-speed train ride leads to profound conversations and unforgettable memories.",
        tags: ["Romance", "Drama"]
    },
    {
        title: "Beijing Opera Legacy",
        code: "HDV-007",
        model: "Zhang Fang",
        studio: "DragonMedia",
        region: "China",
        releaseDate: "2026-03-18",
        duration: "130",
        imgurl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "A deeply moving historical drama following the arduous training and life dedication of a traditional opera performer.",
        tags: ["Drama", "History", "Documentary"]
    },
    {
        title: "Bali Sunset Rhythms",
        code: "HDV-008",
        model: "Dewi Lestari",
        studio: "Archipelago",
        region: "Indonesia",
        releaseDate: "2026-03-22",
        duration: "100",
        imgurl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "A musical documentary capturing traditional acoustic performances live against the stunning sunset background of Bali.",
        tags: ["Travel", "Music", "Documentary"]
    },
    {
        title: "Osaka Night Racing",
        code: "HDV-009",
        model: "Aoi Tsukada",
        studio: "StudioNeo",
        region: "Japan",
        releaseDate: "2026-03-25",
        duration: "112",
        imgurl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "Street racing culture at its absolute peak, featuring modified Japanese sports cars roaring down the loop highways.",
        tags: ["Action", "Cyberpunk"]
    },
    {
        title: "Jeju Island Memories",
        code: "HDV-010",
        model: "Park Min-ji",
        studio: "KWave",
        region: "Korea",
        releaseDate: "2026-03-28",
        duration: "118",
        imgurl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=60",
        vidurl: "https://www.w3schools.com/html/mov_bbb.mp4",
        bio: "A nostalgic journey back to childhood hometowns, discovering old letters and forgotten promises by the ocean side.",
        tags: ["Romance", "Slice of Life"]
    }
];